### ISSUE TITLE
Make the number uncopyable in the tab

### ISSUE THREAD

**Issue by assiless** [kg8m/chrome-show-tab-numbers#21]
Make the number uncopyable in the tab.
for example when bookmarking the title become `№. title`
and more cases just like a bookmark

the number in the tab should be for ui purposes not change data
the number should "behave" just like favicon, can pseudo be a solution?

**Comment by kg8m** [comment]
@assiless 
Thank you for opening this issue. I completely agree with you. However, I don't know how to solve this problem with practical efforts.

**Comment by juanRabaa** [comment]
I don't think thats possible since the extension is changing the `document.title` to add the number.
I guess you could listen to the `chrome.bookmarks.onCreated` event, and remove the number there if the bookmark title matches a tab title + its number.

https://developer.chrome.com/docs/extensions/reference/bookmarks/#event-onCreated
https://developer.chrome.com/docs/extensions/reference/bookmarks/#method-update

**Comment by kg8m** [comment]
@juanRabaa 
Thanks for the advice! The `chrome.bookmarks.onCreated` event looks good (non-bookmark issues remain, but I have no idea now). I’ll try it later.

**Comment by kg8m** [comment]
@juanRabaa @assiless 
I tried the `chrome.bookmarks` API, but it may be difficult to remove the number from a newly created bookmark. 

1. The bookmark object can be obtained via `chrome.bookmarks.onCreated` event.
2. The bookmark title can be updated (and the number removed) via the `chrome.bookmarks.update` function.
3. However, the number is restored because the new bookmark title is overwritten when the user closes the editing dialog box.

![Screenshot 20230918 113111](https://github.com/kg8m/chrome-show-tab-numbers/assets/694547/4639649c-44a2-4420-81c7-733090bb1aae)

I’ll explore to find a solution.

**Comment by NachtaktiverHalbaffe** [comment]
I stumbled upon another (kinda broken) [extension](https://chromewebstore.google.com/detail/tab-number/fijaenjgknobfdombbdchngpamggajpm) which uses the favicons to display the number. Maybe this could be a way to mitigate such problems? It also has drawbacks e.g. losing favicons (I dont know if you can change the aspect ratio of favicons, otherwishe you have to replace the fav icon instead of adding it behind), but maybe this could be a way to rethink things or to offer both ways and let the user choose via a configuration
